### PR TITLE
Bundle

### PR DESCRIPTION
**Pull request by harrysarson**
Would address #8.

Currently, the package structure that (I hope(!)) would be published to npm is the following:

```
dist/
  UnitMath.js  UnitMath.min.js
es/
  UnitMath.js  UnitMath.min.js
src/
  approx.js  Parser.js  Unit.js  UnitStore.js
index.js
LICENSE
README.md
package.json
```

* In the `dist` directory are two `umd` bundles (one minified, both babeled to work on ie 11).
* In the `es` directory are two es modules (one minified, neither are babeled - I reasoned that if a browser can support es modules it can support everything else).
* `index.js` is a common js file that uses the [esm package](https://www.npmjs.com/package/esm) to load the source files. Therefore, in node there is no transpilation needed.
* I have used [rollup](https://www.npmjs.com/package/rollup) for bundling, I initially tried webpack but found that rollup required less configuration and was more straight forward to use.
* I have made some fairly opinionated changes here (including swapping `.npmignore` blacklist for a whitelist of files in `package.json`) but I am very happy to make any and all changes - this is only a proposal.

What do you think?

### CODE REVIEW

**Comment by harrysarson** [comment]
The approach I have taken is heavily inspired by [redux](https://github.com/reduxjs/redux) which I used as an example of a fairly small but very popular library.

The use of esm is inspired by https://github.com/lodash/lodash/issues/3745. The (not yet implemented) plan for the next major version of lodash is to use the esm package.

**Comment by ericman314** [comment]
Ok, sounds like a plan. I think I prefer `UnitMath`, but `unitmath` would also be fine.

**Comment by harrysarson** [comment]
Additionally, what should the bundle expose? Currently the functions exposed by the bundle are those exposed by `Unit.js` but should we, for example, allow access to `UnitStore`?

**Comment by ericman314** [comment]
I haven't decided on `UnitStore` yet. Right now, it's exposed under `_unitStore` for te purpose of running tests. I might be able to move those tests that only use `UnitStore` into their own file. But I don't see a reason at this time to make it publicly accessible.

**Comment by harrysarson** [comment]
In which case, I think this is good to go - from my end atleast

**Comment by ericman314** [comment]
Great. Thank you so much for putting this together!

**Comment by ericman314** [comment]
Version 0.1.0 has been released!

**Pull request merged**
