### PR TITLE
Update package.json to support modern bundlers like Vite

### PR DESCRIPTION
**Pull request by fezproof**
I tried this library and it works great, but was having some issues with TS and Vite when importing.

image

There are some issues with newer versions of TS and Vite that require strict bundling rules. If we point the `import` part of this package to the es bundled code (matching `module`) it should avoid a whole bunch of problems.

Making this change locally fixes this. See here:
image
image

### CODE REVIEW

**Comment by fezproof** [comment]
@ericman314 just wanted to see if this project is still alive?

**Comment by ericman314** [comment]
Sorry. I've recently gotten much busier in my personal and work life since starting this project, so I don't have as much time to work on it. I haven't completely abandoned it, but progress will be slow. I will try to get to this soon, but I can't make any promises about a timeline.

**Comment by ericman314** [comment]
Thanks for your patience, and especially thanks for the improvement! For some reason it never occurred to me to try this library in a TypeScript project, but your fix works great!

**Comment by ericman314** [comment]
Published as 1.1.1

**Pull request merged**
